"""initial schema

Revision ID: 53855ae17c1b
Revises: 
Create Date: 2026-06-23 19:52:43.110215
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '53855ae17c1b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity',
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=False),
    sa.Column('handle_lower', sa.String(length=64), nullable=False),
    sa.Column('recovery_code_hash', sa.String(length=128), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('consent_version', sa.String(length=32), nullable=False),
    sa.Column('consent_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('fingerprint')
    )
    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_handle_lower'), ['handle_lower'], unique=True)
        batch_op.create_index(batch_op.f('ix_identity_token'), ['token'], unique=True)

    op.create_table('run',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('ruleset_version', sa.String(length=64), nullable=False),
    sa.Column('content_version', sa.String(length=64), nullable=False),
    sa.Column('modded', sa.Boolean(), nullable=False),
    sa.Column('manifest_hash', sa.String(length=128), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('daily_date', sa.String(length=16), nullable=True),
    sa.Column('class_id', sa.String(length=64), nullable=False),
    sa.Column('foe_id', sa.String(length=64), nullable=True),
    sa.Column('seed', sa.String(length=128), nullable=False),
    sa.Column('spec_ref', sa.String(length=128), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('terms', sa.Integer(), nullable=True),
    sa.Column('real_time_ms', sa.Integer(), nullable=True),
    sa.Column('depth_reached', sa.Integer(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('instruments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_content_version'), ['content_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_daily_date'), ['daily_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_foe_id'), ['foe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_ruleset_version'), ['ruleset_version'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_ruleset_version'))
        batch_op.drop_index(batch_op.f('ix_run_kind'))
        batch_op.drop_index(batch_op.f('ix_run_foe_id'))
        batch_op.drop_index(batch_op.f('ix_run_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_run_daily_date'))
        batch_op.drop_index(batch_op.f('ix_run_content_version'))
        batch_op.drop_index(batch_op.f('ix_run_class_id'))

    op.drop_table('run')
    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_token'))
        batch_op.drop_index(batch_op.f('ix_identity_handle_lower'))

    op.drop_table('identity')
    # ### end Alembic commands ###
